[tox]
envlist =
    pyroma
    ruff
    mypy
    py


[testenv]
commands =
    pytest --cov=prodec tests/
extras =
    testing
description = Run tests to check code validity.

[testenv:pyroma]
commands =
    pyroma .
deps =
    pyroma
skip_install = true
description = Make sure pyproject.toml is properly written out.

[testenv:ruff]
skip_install = true
deps =
    ruff
commands =
    ruff check .
description = Lint the codebase with ruff.

[testenv:mypy]
extras =
    lint
commands =
    mypy src/prodec
description = Type-check the codebase with mypy.
